#include <stdint.h>
#include <stdbool.h>
typedef char byte;
typedef char sbyte;
typedef int undefined;
typedef int code;
typedef unsigned int uint32_t;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef unsigned int unkuint;
typedef unsigned char unkbyte10;
// types that header don't work
typedef int __jmp_buf_tag;
typedef int stat;
typedef int dirent;
typedef int DIR;
typedef int tm;
typedef int timeval;
typedef int __timezone_ptr_t;
typedef int __sighandler_t;
typedef int __suseconds_t;
typedef int __time_t;
typedef int fd_set;
typedef int __mode_t;
typedef int fd_set;
typedef int _IO_FILE;
typedef int FILE;
typedef int __ssize_t;
typedef int addrinfo;
typedef int utmpx;
typedef int passwd;
typedef int sysinfo_t;
typedef int sigaction;
typedef int utsname;
typedef int __ino_t;
typedef int timespec;
typedef int _union_1454;
typedef int itimerspec;
typedef int sigevent;
typedef int __locale_t;
typedef int uint2_t;
typedef int __nlink_t;
typedef int statfs;
typedef int wctype_t;
typedef int termios;
typedef int speed_t;
typedef int cc_t;
typedef int rlimit;
typedef int cpu_set_t;
typedef int sysinfo_t;
typedef int __compar_fn_t;
typedef int iconv_t;
typedef int utimbuf;
typedef int group;
typedef int timezone;
typedef int __blksize_t;
typedef int __blkcnt_t;
typedef int BADSPACEBASE;
